apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-spring-boot2-test-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        default: /workspace/extracted/Dockerfile
      - name: pathToContext
        default: /workspace/extracted
  outputs:
    resources:
      - name: docker-image
        type: image
  steps:
    - name: test
      securityContext:
        privileged: true
      image: kabanero/java-spring-boot2:0.3
      command:
        [
          "/bin/bash",
          "-c",
          "cd ../.. && rm -r /project/user-app && ln -s ${inputs.params.pathToContext} /project/user-app && cd project/user-app/ && ls && $APPSODY_TEST",
        ]
      env:
        - name: gitsource
          value: git-source
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
