apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-spring-boot2-test-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToContext
        default: /workspace/extracted
  steps:
    - name: test
      securityContext:
        privileged: true
      image: kabanero/java-spring-boot2:0.3
      command:
        [
          "/bin/bash",
          "-c",
          "ln -s ${inputs.resources.git-source.path} ${inputs.params.pathToContext} && cd ${inputs.params.pathToContext} && pwd && ls && $APPSODY_TEST",
        ]
      env:
        - name: gitsource
          value: git-source
