apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-spring-boot2-test-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  steps:
    - name: test
      image: kabanero/java-spring-boot2:0.3
      workingdir: ${inputs.resources.git-source.path}
      command: ["/bin/bash", "-c", "pwd && ls && $APPSODY_TEST"]
